### ISSUE TITLE
不支持的操作系统Debian GNU/Linux 11 (bullseye)

### ISSUE THREAD

**Issue by aisuyi065** [e5sub/hst#1]
Last-modified header missing -- time-stamps turned off.
2023-06-06 17:59:53 (139 MB/s) - ‘/home/grafana/prometheus/rules.yml’ saved [6619/6619]

不支持的操作系统
root@debian:~# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@debian:~#

**Comment by e5sub** [comment]
你再试试,刚更新了安装脚本
